--- #YAML:1.0
name:                App-BCVI
version:             3.02
abstract:            Back-channel vi, a shell utility to proxy commands back over ssh
license:             ~
author:              
    - Grant McLean <grantm@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
