--- #YAML:1.0
name:               App-BCVI
version:            3.03
abstract:           Back-channel vi, a shell utility to proxy commands back over ssh
author:
    - Grant McLean <grantm@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:        5.008
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
